### ISSUE TITLE
CBF and CPFP first use

### ISSUE THREAD

**Issue by jandrieu** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#10]
In chapter 5 https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/05_0_Controlling_Bitcoin_Transactions.md#chapter-five-controlling-bitcoin-transactions , it uses CBF and CPFP without explaining what they are. They get de-referenced in the next chapter, but on this page there was definitely a moment of confusion wondering what these terms are.

**Comment by shannona** [comment]
A year later, I'm finally running through the tutorial to update and polish it. I've now got this in. Thanks!
