### ISSUE TITLE
Scripting a Multisig

### ISSUE THREAD

**Issue by Keerthana-Jayakumaran** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#101]
Hi,
I read this [https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/08_4_Scripting_a_Multisig.md](https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/08_4_Scripting_a_Multisig.md ).It is good.
I am working on creating simple p2sh script. But first round of validation can be done easily. Can you please tell about how to do the second round of validation that is deserializing the redeemscript and combine with the operands and do the operation?
Because when we give a scriptsig for a locking script, some of the values will be  pushed on to stack initially follwed by whole redeemscript pushed as element into the stack. In that case, how will you deserialize and verify the internal script?

**Comment by shannona** [comment]
Please let us know if there is anything that you think is specifically lacking from the document, and we'll take a look at it as we update.
