### ISSUE TITLE
Chinese Translation?

### ISSUE THREAD

**Issue by qbig** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#102]
Hi, I am offering to contribute a Chinese translation. Anyway to get started?

**Comment by baxter2** [comment]
I was wondering the some thing but for Japanese. Is it okay to make a PR for translations?

**Comment by ChristopherA** [comment]
I would like to see both translations as PRs. Be aware that we need to update the course to 0.19. I’m also considering moving the course to Blockchain Commons community.

**Comment by baxter2** [comment]
I’m not familiar with the Blockchain Commons Community. Would you be able to share a link, pointing me in the direction?

**Comment by ChristopherA** [comment]
https://github.com/BlockchainCommons

**Comment by shannona** [comment]
We have started incorporating PRs and Issues. Afterward I expect we'll be moving to the BlockchainCommons Github and then doing a full update for 0.19. My suggestion would be to hold on translations until that is done, hopefully in the next few months.
