### ISSUE TITLE
Chapter 06_01: pubkey information

### ISSUE THREAD

**Issue by simonschmoll** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#104]
The old command for getting the public key of an address is described in Chapter 06_01:
```machine2$ bitcoin-cli -named validateaddress address=$address2```

The new command since 0.17.0 would be:
```machine2$ bitcoin-cli -named getaddressinfo address=$address2```

**Comment by shannona** [comment]
Yep, just updated that from your other PR. Thank you!
