### ISSUE TITLE
6_1 Signing multisig transaction CLI command

### ISSUE THREAD

**Issue by simonschmoll** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#105]
The following command (chapter 6_1_Sending_a_Transaction_to_a_Multisig) can not be executed because env variable $address1 is an address and not a pub key: 
```
machine1$ bitcoin-cli -named createmultisig nrequired=2 keys='''["'$address1'","0367c4f666f18279009c941e57fab3e42653c6553e5ca092c104d1db279e328a28"]'''
```

Therefore $address1 should be changed to the pubkey of address1 (same as with address2).

**Comment by simonschmoll** [comment]
In the description it says that bitcoin-cli does recognise own addresses and convert them to pubkeys. In my case it just said ```Invalid public key:```. address1 was created (```bitcoin-cli getnewaddress```) directly before the multisig transaction was built. Maybe someone could explain why this doesn't work in my case.

**Comment by ChristopherA** [comment]
Which version of bitcoind are you using?

Now that Bitcoin-Core is at 0.19, there are a number of new topics such as PSBT (partially-signed bitcoin transactions) etc. that need to be addressed, as well as old topics since now bech-32 addresses are the default. It is unlikely that we'll get to them before January though.

**Comment by simonschmoll** [comment]
The version I am currently using is v0.18.1. 

Thanks for this awesome guide, it is a great way of getting to know bitcoin.

**Comment by shannona** [comment]
Thanks, it looks like there were a few changes in place by 0.18: as you note the createmultisig command no longer will auto-convert the address like it did in older versions. In addition, validateaddress no longer shows the pubkey! I've updated accordingly.
