### ISSUE TITLE
VPS Stackscript setup 

### ISSUE THREAD

**Issue by daemon-dash** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#115]
I am trying to setup the a VPS using linode but when I try to save the script I get an 'Internal Server' error at the top? Any ideas? 

<img width="541" alt="Screen Shot 2020-03-24 at 4 05 55 PM" src="https://user-images.githubusercontent.com/53798994/77476948-9b633880-6de9-11ea-9dac-9adebdfb3677.png">

**Comment by ChristopherA** [comment]
I'm not sure. At first glance, maybe there are some limits on what characters you can use in a label?

Also note there is a more sophisticated stackscript that also installs Tor at https://github.com/BlockchainCommons/Bitcoin-StandUp-Scripts and if you have a Mac there is an app https://github.com/BlockchainCommons/Bitcoin-StandUp-MacOS that make it easy to install a testnet node on your own laptop.

Let us know if either of these address your problem.

-- Christopher Allen

**Comment by shannona** [comment]
Closing this. If there are continued problems (or you can flag your solution), please let us know.
