### ISSUE TITLE
Section 2.1 doesnt work on Debian 10?

### ISSUE THREAD

**Issue by matthiasdebernardini** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#116]
Hi I tried to follow the setting up guide but I was not able to get it to work on Debian 10 on digital ocean. 

I was however able to successfully follow this https://www.digitalocean.com/community/tutorials/initial-server-setup-with-debian-10 

this 
https://medium.com/@meeDamian/bitcoin-full-node-on-rbp3-revised-88bb7c8ef1d1

and I also found this 
https://github.com/jtesta/ssh-audit

Maybe its time to update the guide? 

What is currently in Section 2.1 is really complicated IMO.

**Comment by shannona** [comment]
Certainly is. I'm adding it to our TODO.

(As for the fact that it's complicated: yes. That's why we suggest using the Linode StackScript or a program such as Bitcoin Standup at Blockchain Commons.)
