### ISSUE TITLE
Sending Coins the Easy Way: Transaction never broadcasts 

### ISSUE THREAD

**Issue by leobauza** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#14]
I am following along on section 4.1 and when I try to do:

`bitcoin-cli sendtoaddress [address] [amount]`

Everything seems to work fine but my transaction stays with 0 confirmations (over 24 hours now). When I check the transaction the way the tutorial suggests everything looks the same.

```
{
  "amount": -0.10000000,
  "fee": -0.00022400,
  "confirmations": 0,
  "trusted": false,
  "txid": "888e82fc464e6f520ffd016aadbc1aeeb52c69ca51faf57f3573ec5c90be1a9c",
  "walletconflicts": [
    "e8a1ea84e968bc1e4cd04e9f762e5145e3c620bd70d250ce422df71d32c00d48",
    "aad4eb89a13fd92268363e18f4e92cd890622e58494ff1179df579a4edff6bef"
  ],
  "time": 1511656829,
  "timereceived": 1511656829,
  "bip125-replaceable": "unknown",
  "details": [
    {
      "account": "",
      "address": "2N8hwP1WmJrFF5QWABn38y63uYLhnJYJYTF",
      "category": "send",
      "amount": -0.10000000,
      "vout": 0,
      "fee": -0.00022400,
      "abandoned": false
    }
  ],
  "hex": "020000000151dd79ce6ffc47739b17e5f984942eab0e48d6243a09ca4136bf8730c0d5b099000000006a4730440220212b8fbfdd7119dbb7473dad2493b4e40c7a82dc1b463075030242a8d97556770220300fc6be4d446fef32a448a2e372982933bdc3a8a6f00119c5b0869b5bcefe430121026910802d0ac183a6195f5bac6dd9e9d613dbe2fe96275cfbe2884bdc4a1a8a53feffffff02809698000000000017a914a9974100aeee974a20cda9a2f545704a0ab54fdc8780b62607000000001976a9142c674fa2afe460ad7eaf0d9dd97c85461966fd7688ac2df11200"
}
```

I also expected to see my transaction in the mempool of my node but that just returns an empty array. When I pass true to `bitcoin-cli getrawmempool true` I get an empty json object.

I am wondering if there is something that would prevent my node from broadcasting transactions? Or if my mempool is somehow set up wrong?

Great tutorial, it's thought me a lot so far. I will just move to the next sections and hopefully figure this out later. Cheers.

**Comment by brunocvcunha** [comment]
@leobauza It looks like you spent the same output twice, because of the `walletconflicts` field that you posted here.

Take a look at this discussion: https://bitcoin.stackexchange.com/questions/49364/bitcoin-core-0-13-jsonrpc-interface-conflicted-transactions

**Comment by madztheo** [comment]
I don't know if you were able to figure it out or not, but I came across the same issue when creating a transaction through `sendtoaddress`. It didn't broadcast my transaction properly either. But I found a workaround. Use `bitcoin-cli gettransaction <txid>`with the id of your transaction, copy its raw format that you can find in the `hex` field. Then use it with the command `bitcoin-cli sendrawtransaction <rawtransaction>` as you would do with a raw transaction you created yourself, and your transaction should be broadcast just fine.  If your transaction is still not broadcast, you could still cancel it as it has received any confirmation with `bitcoin-cli abandontransaction <txid>`.

**Comment by leobauza** [comment]
Thanks @brunocvcunha and @madztheo. Turns out for some reason my `bitcoin.conf` file was set up to not broadcast transactions, so I had to make the change there. Not sure if the default is to not broadcast or if I did something else weird when setting things up. But tweaking the conf made everything work.

**Comment by madztheo** [comment]
@leobauza Yes indeed, adding `walletbroadcast=1` to `bitcoin.conf` does seem to do the trick. But it's a bit weird considering that the default value of `walletbroadcast`should be 1.

**Comment by leonardo-sj** [comment]
I had the same issue, but with no walletconflicts (see below).
I added walletbroadcast=1 to bitcoin.conf and it was apparently solved.
Is that part of tutorial or did I missed something ?
```
[
  {
    "account": "",
    "address": "mqjmwiHQigse1sUSPCcGBu8LLugUyEqZL8",
    "category": "receive",
    "amount": 2.00000000,
    "label": "",
    "vout": 0,
    "confirmations": 229,
    "blockhash": "000000000000083aaeeeb4dffa299288fc9048b20c91b0bcee1098a39034c62b",
    "blockindex": 3,
    "blocktime": 1515899490,
    "txid": "90ef6c0b4c5800e7d1234f54257e5acb4e33cf6428481e82e37994d126b3452e",
    "walletconflicts": [
    ],
    "time": 1515899490,
    "timereceived": 1515899514,
    "bip125-replaceable": "no"
  }, 
  {
    "account": "",
    "address": "n2eMqTT929pb1RDNuqEnxdaLau1rxy3efi",
    "category": "send",
    "amount": -0.10000000,
    "vout": 1,
    "fee": -0.00022600,
    "confirmations": 0,
    "trusted": false,
    "txid": "8006e4c0dc6a46b2223bdf7928fecfbd3e5666166f6fec2e7d7978be69cfea37",
    "walletconflicts": [
    ],
    "time": 1516065119,
    "timereceived": 1516065119,
    "bip125-replaceable": "unknown",
    "abandoned": false
  }
]
```

**Comment by shannona** [comment]
Thanks for the highlighting & debugging of this, folks. I've added walletbroadcast=1 to the default bitcoin.conf.
