### ISSUE TITLE
Better Bitcoin Script debugging tool — btcdeb

### ISSUE THREAD

**Issue by ChristopherA** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#19]
@kallewoof has written a better Bitcoin Script debugging tool at https://github.com/kallewoof/btcdeb — we should re-write chapter 7 to use it.

@shannona, what do you think? @luke-jr can you review Kalle's code?

**Comment by luke-jr** [comment]
Would be nice if there was some indication what Core commit it was based on... or better yet, used libbitcoinconsensus XD

**Comment by kallewoof** [comment]
@luke-jr Good point. I should perhaps peg it to the latest stable (it's using master right now).

Using libbitcoinsensus sounds like an obvious next step. I kind of ripped out everything not needed to get basic functionality in place, but I do want some stuff that's currently not possible.

**Comment by codeShark149** [comment]
Running the code in Appendix II for getmininginfo returns error with error code 5 (concatenation error). I am running Bitcoin-core 16.0. libbitcoinrpc documentation specifies it has been tested up till version 12. Can that be a problem??

**Comment by kallewoof** [comment]
Not done, but I am working on making the revision equal the minor of bitcoin core. So btcdeb for bitcoin core 0.20.0 would be btcdeb X.Y.20.

**Comment by kallewoof** [comment]
See https://twitter.com/kallewoof/status/1219418563586510849

**Comment by shannona** [comment]
Added to [TODO.md](TODO.md).
