### ISSUE TITLE
Chap 3 export BITCOIN and BITCOINPLAIN, vars not persistenting on ssh logout

### ISSUE THREAD

**Issue by guilsa** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#22]
Thanks for this wonderful repo. Such an exciting place to learn about bitcoin in a linear fashion.

I have been following Chap 3 meticulously via the Linode VPS but have noticed that the [setup variables](https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/02_1_Setting_Up_a_Bitcoin-Core_VPS_by_Hand.md#setup-variables) instructions use `export` which to me preserves both variables only across sub-shells. If I logout, log back in and try `echo $BITCOIN `, it returns blank. The crontab entry to start the bitcoin daemon whenever the VPS restarts also won't work unless I go through the setup variables instructions again. Am I missing something?

**Comment by guilsa** [comment]
Forgot to mention that I keep having to source ~/.bash_profile on each ssh session.

**Comment by guilsa** [comment]
Could it be my Linode Boot Settings > Run Level > set to Default Run Level instead of init=/bin/bash?

**Comment by guilsa** [comment]
Looks like its running out of memory. I'm on a Linode 1G: 1 CPU(s), 20G Storage, 1G RAM. Does this issue still hold true though or are the exported vars not persisting because it's crashing instead of properly shutting down?

**Comment by shannona** [comment]
The $BITCOIN and BITCOINPLAIN variables are only used in the setup. I've added a warning that you need to do all the setup in one session. I suspect your .bash_profile is related to #24. We do suggest Debian as the default setup, but we're going to see if we can get Ubuntu working too.
