### ISSUE TITLE
bash_profile not working for ubuntu

### ISSUE THREAD

**Issue by pbengert** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#24]
Hello,
I am aware you are using debian, but I think many people will follow this on their standard linux distro. Ubuntu (16.04) is not reading from bash_profile properly but instead from bashrc (at least in the desktop enviroment, might work at a login shell), so writing the aliases won't work in ubuntu (used here: https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/02_1_Setting_Up_a_Bitcoin-Core_VPS_by_Hand.md and https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/03_1_Verifying_Your_Bitcoin_Setup.md)
You might consider adding something like ('use ~/.bashrc instead of ~/.bash_profile on ubuntu')

**Comment by cavapoo2** [comment]
Can't you just do source .bash_profile ?

**Comment by shannona** [comment]
One is used for login shells and the other for interactive non-login shells (nothing to do with Ubuntu vs Debian). I'm updating things to put the same info in both.
