### ISSUE TITLE
Explanation of sed program missing

### ISSUE THREAD

**Issue by cavapoo2** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#31]
```
$ integer=1546288031
$ hex=$(printf '%08x\n' $integer | sed 's/^\(00\)*//')
$ echo $hex
```

https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/08_2_Building_the_Structure_of_P2SH.md

**Comment by shannona** [comment]
We've got a few different command-line text programs like sed and tr that we don't provide full explanations of because they're just tools, used as part of command-line prompts, not actual Bitcoin features.
