### ISSUE TITLE
Upgrade to 0.16

### ISSUE THREAD

**Issue by yashbhutwala** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#33]
Since a new major version of Bitcoin Core is released [0.16.0](https://github.com/bitcoin/bitcoin/blob/master/doc/release-notes/release-notes-0.16.0.md), I was wondering if there's any plans to upgrade these tutorials. I'm starting a branch off of my [fork] (https://github.com/yashbhutwala/Learning-Bitcoin-from-the-Command-Line/tree/0.16), reviews are welcomed. PR #34.

**Comment by shannona** [comment]
Yep! I've got a good TODO list of things needed to bring this tutorial into a "publishable"/public form, and the next-to-last is to walk through the tutorial and make sure it all works with 0.16.

@ChristopherA has also noted that we should look at any new wallet functionality in 0.16 to see if that should be added.

**Comment by ChristopherA** [comment]
Yes, we are hoping to dive into update for 0.16 soon. Longer term Tor, Fibre, Blockstream Satellite, and probably C-Lightning.

But PRs are always welcome!!

**Comment by yashbhutwala** [comment]
@shannona right now I'm going through the entire tutorial with 0.16 and updating as I go. Have you shared that list of TODOs anywhere? I'd love to help where I can.

**Comment by shannona** [comment]
PR #34 by @yashbhutwala has a great first step here, which I'll be consulting as I take my own pass through for 0.16 in the next few weeks.
