### ISSUE TITLE
Address does not refer to key

### ISSUE THREAD

**Issue by lmazur** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#36]
Hello, I have been going through the steps, and tried signing a message per the steps, and I get the Address does not refer to key errorl

Hello, I am new here.

I am experimenting with a full node, and setup a new node on ubuntu - Core 0.16.0.
I'm running my bitcoind in test-net

I'm running a test-net bitcoin daemon.

Whenever I try to sign a message with my pub key, it shows this error

Steps:

1. bitcoin-cli getnewaddress
--> It produced an address: 2N2yv1XcYfNXR54J7ZJvBxY6ZnmZFbz89tm

2. bitcoin-cli signmessage "2N2yv1XcYfNXR54J7ZJvBxY6ZnmZFbz89tm" "Hello there"

--> Get following error
error code: -3
error message:
Address does not refer to key

This is pretty vanilla functionality - why is this happening and how to address?

Thank you in advance

**Comment by Goosie** [comment]
This is happening because of the update to segwith. Signmessage is not yet into this update, see:  https://bitcointalk.org/index.php?topic=3225732.msg33564199

A workarround is to create a new address bij adding legcy behind the command like:
bitcoin-cli -testnet getnewaddress "" legacy

**Comment by shannona** [comment]
I've updated to use the legacy version of getnewaddress.

**Comment by lmazur** [comment]
thanks!
