### ISSUE TITLE
In Section 03_3 Signmessage won't work because of segwith

### ISSUE THREAD

**Issue by Goosie** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#40]
In Section https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/03_3__Interlude_Using_Command-Line_Variables.md

Signmessage won't work because of the segwith update. More info about this here: https://bitcointalk.org/index.php?topic=3225732.msg33564199

A workarround is to create a newaddress by adding legacy behind the command, like:
bitcoin-cli -testnet getnewaddress "" legacy

**Comment by ChristopherA** [comment]
Thanks. I had missed this in the latest update. 

Some debate on future of signmessage at https://github.com/bitcoin/bitcoin/issues/10542

**Comment by shannona** [comment]
I have updated to use the legacy argument.
