### ISSUE TITLE
error: couldn't connect to server: unknown (code -1)

### ISSUE THREAD

**Issue by raibosome** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#47]
Hi Christopher,

I have just started to follow your tutorial for an intro to Bitcoin and I think it's awesome.

Right now, my Bitcoin daemon is downloading the blocks (testnet). However, I notice that after downloading about 600,000 out of 1,355,036 blocks, the server got disconnected. Only upon running the command `btcblock` do I get the following message:

```
error: couldn't connect to server: unknown (code -1) (make sure server is running and you are connecting to the correct RPC port)/1355033
````

I have tried restarting the daemon and the download, and even rebooted my VPS, but I will always get to the same error. Any tips on this?

**Comment by raibosome** [comment]
Ooops actually solved it by increasing the memory from 2GB to 4GB. Closing this issue.

**Comment by shannona** [comment]
Which setup were you attempting, @raibosome? Was this a non-pruned mainnet? Or something else? (I want to make sure our machine requirement listings are still right.) Thanks!
