### ISSUE TITLE
SignRawTransaction example no longer works

### ISSUE THREAD

**Issue by harding** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#48]
URL: https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/04_2_Creating_a_Raw_Transaction.md#sign-the-raw-transaction

I don't think[1] this works with Bitcoin Core 0.16.0 and above because its wallet defaults to using P2SH-wrapped segwit and segwit requires passing the value of each input being signed to signrawtransaction.  For more information, please see this related issue: https://github.com/bitcoin-dot-org/bitcoin.org/issues/2538

[1] I don't see where in the tutorial it explains to the user how to get an address, so I'm assuming they're just getting whatever address the wallet returns by default, which would be P2SH-wrapped segwit in 0.16.0 and above.  If the docs don't already explain how to get an address and I just missed it, I'd suggest that you make that explicit.

**Comment by shannona** [comment]
The problem is indeed that 0.16 produces a P2SH-wrapped segwit address. I've updated to ensure a legacy address that can actually be signed using the current version of Bitcoin Core.

**Comment by RobertBohn** [comment]
In Bitcoin Core 0.17.0 the signrawtransaction generates this error:

signrawtransaction is deprecated and will be fully removed in v0.18. To use signrawtransaction in v0.17, restart bitcoind with -deprecatedrpc=signrawtransaction.

Projects should transition to using signrawtransactionwithkey and signrawtransactionwithwallet before upgrading to v0.18

**Comment by lucianobargmann** [comment]
And I am reeealy having a fight over the weekend with this :) Errors are not very helpful, but if I ever get it working, I will add the correct format for it here.
