### ISSUE TITLE
btcinfo has an outdated command (bitcoin-cli getinfo) for 0.16.0

### ISSUE THREAD

**Issue by leonardo-sj** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#49]
~# btcinfo
  "balance": 0.00000000,
error code: -32601
error message:
getinfo

This call was removed in version 0.16.0. Use the appropriate fields from:
- getblockchaininfo: blocks, difficulty, chain
- getnetworkinfo: version, protocolversion, timeoffset, connections, proxy, relayfee, warnings
- getwalletinfo: balance, keypoololdest, keypoolsize, paytxfee, unlocked_until, walletversion

bitcoin-cli has the option -getinfo to collect and format these in the old format.

**Comment by leonardo-sj** [comment]
Suggested fix:

alias btcinfo='bitcoin-cli getwalletinfo | egrep "\"balance\""; bitcoin-cli getnetworkinfo | egrep "\"version\"|connections"; bitcoin-cli getmininginfo | egrep "\"blocks\"|errors"'

**Comment by shannona** [comment]
Should be resolved in the new version of the setup:
```
user1@btctest:~$ btcinfo
  "balance": 0.00000000,
  "version": 160000,
  "connections": 10,
  "blocks": 1356510,
```
Here's the updated alias, from section 3.1:
```
alias btcinfo='bitcoin-cli getwalletinfo | egrep "\"balance\""; bitcoin-cli getnetworkinfo | egrep "\"version\"|connections"; bitcoin-cli getmininginfo | egrep "\"blocks\"|errors"'
```
Thanks!
