### ISSUE TITLE
dumpwallet uses home directory not current directory

### ISSUE THREAD

**Issue by jandrieu** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#5]
https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/03_3_Setting_Up_Your_Wallet.md#optional-view-your-private-keys

> To look at all the keys in your wallet, type bitcoin-cli dumpwallet mywallet.txt. This will create a mywallet.txt file in your current directory with a long list of private keys, addresses, and other information.

However, this command places mywallet.txt in the user's home directory.

**Comment by unsystemizer** [comment]
No, it doesn't. 

One can set an absolute or relative path. A relative path (`wallet.txt`) places the file relative to bitcoind.

**Comment by shannona** [comment]
Cover with PR #6.
