### ISSUE TITLE
Accessing bitcoin with python

### ISSUE THREAD

**Issue by tHeMaskedMan981** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#50]
when will this part get completed? approximate date? and right now I wanted some way to connect with the bitcoin using python. Do u have something in mind I can start from?

**Comment by shannona** [comment]
It's unfortunately months away, as we're going to loop back through the whole tutorial and do some work polishing and expanding it and then write the new Lightning section before we get back to the code.

Fortunately, we have some Python code that was suggested as a PR, but was a little sparse, but which I think might help you get started:
https://github.com/pinheadmz/Learning-Bitcoin-from-the-Command-Line/blob/9555c3bf1c2f7fb6bdb7d34240d07e97df7b8723/12_6_Accessing_Bitcoind_with_Python.md
