### ISSUE TITLE
Alias btcinfo gives error on bitcoind 0.16.2

### ISSUE THREAD

**Issue by wolfmcnally** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#59]
Using Bitcoin Core 0.16.2. In the file [here](https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/02_1_Setting_Up_a_Bitcoin-Core_VPS_by_Hand.md), your `btcinfo` alias no longer works. I get:

```
This call was removed in version 0.16.0. Use the appropriate fields from:
- getblockchaininfo: blocks, difficulty, chain
- getnetworkinfo: version, protocolversion, timeoffset, connections, proxy, relayfee, warnings
- getwalletinfo: balance, keypoololdest, keypoolsize, paytxfee, unlocked_until, walletversion
```

**Comment by shannona** [comment]
I may need to sync my script (which is awaiting figuring out what's going on in #72) but as soon as I do, this will be fixed:
```
$ btcinfo
  "balance": 0.00000000,
  "version": 170000,
  "connections": 6,
  "blocks": 90956,
```
