### ISSUE TITLE
Interested in starting Italian translation

### ISSUE THREAD

**Issue by gianlock** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#596]
Hi, 
i'm interested in starting italian translation of the contents these amazing project!

I was wondering if it make sense to start now or is there a new Release milestone coming?

If it's ok to start now, can you create a new branch for my translation?

Thanks, 
gianlock

**Comment by Jetro-Costa** [comment]
I suggest starting in the personal repository, many files so unedited for two years; then simply open a pull request.

**Comment by ChristopherA** [comment]
We’d love to see an Italian translation!

The next milestone for the course is a big one, such as converting from regtest to signet, and taproot by default. As such I don’t believe we can get to it by the Blockchain Commons core team before summer, which at best is release in fall. If we get more volunteers over summer it might be faster.

Thus I suggest you work based on this version.
