### ISSUE TITLE
Steps for creating Testnet node on AWS

### ISSUE THREAD

**Issue by wolfmcnally** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#60]
I have done a blog post of the steps it took me to set up a Testnet node on AWS [here](http://wolfmcnally.com/115/developer-notes-setting-up-a-bitcoin-node-on-aws/). You are free to incorporate it into the eBook.

**Comment by shannona** [comment]
Lovely alternative! I didn't want to create a new institutional debt of keeping this up-to-date, so instead I created a new section 2.3 that links this (and Bitcoin Standup ... and if we come across other means, those).
