### ISSUE TITLE
Broken link in 06.5 Sending a Transaction with Data

### ISSUE THREAD

**Issue by JayDugger** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#61]
Clicking the link in the sentence 

Again, remember that you can look at this transaction using a blockchainexplorer:
https://live.blockcypher.com/btc-testnet/tx/3a62b396afb8d8a59ebe7b9e52d6aa2485f1082a1d3fc6ece61fb8b55373823d/

gives a page with the error message.

No transaction found with the hash 3a62b396afb8d8a59ebe7b9e52d6aa2485f1082a1d3fc6ece61fb8b55373823d

I expected this to lead to a page with transaction information.

The next link in the section leads to a page with transaction information as expected.

**Comment by shannona** [comment]
Wow. That's curious that Blockcypher lost track of it! Thanks, substituting with another explorer.
