### ISSUE TITLE
CSV - Small typo in printf command 

### ISSUE THREAD

**Issue by Janaka-Steph** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#65]
Hello,

I noticed a small typo in a shell command, in [9.3: Using CSV in Scripts, paragraph create-a-csv-relative-time](https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/83755c27f3fdf67c5f075ac7293ebd67b43295d3/09_3_Using_CSV_in_Scripts.md#create-a-csv-relative-time).

Actual
```
Finally, bitwise-or the 23rd bit into the hex value you created:

$ relativevalue=$(printf '%x\n' $((0x$hexvalue | 0x400000)))
$ echo $relativevalue
4224679
```

Expected
```
Finally, bitwise-or the 23rd bit into the hex value you created:

$ relativevalue=$(printf '%d\n' $((0x$hexvalue | 0x400000)))
$ echo $relativevalue
4224679
```

It should be `%d\n` to get a decimal value.

**Comment by shannona** [comment]
We're creating a hex value for use in a transaction, not a decimal value for use in viewing.
