### ISSUE TITLE
signrawtransaction should be replaced by signrawtransactionwithwallet

### ISSUE THREAD

**Issue by RobertBohn** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#69]
The ```signrawtransaction``` command no longer works using default setting in the latest bitcoin core version v0.17.
```
signrawtransaction is deprecated and will be fully removed in v0.18. To use signrawtransaction in v0.17, restart bitcoind with -deprecatedrpc=signrawtransaction.
Projects should transition to using signrawtransactionwithkey and signrawtransactionwithwallet before upgrading to v0.18
```
These sections should be converted to use ```signrawtransactionwithwallet```

4.2 Creating a Raw Transaction
4.3 Creating a Raw Transaction with Named Arguments
4.5: Sending Coins with Automated Raw Transactions

**Comment by shannona** [comment]
Thanks! We're finally stepping back to update the course and have fixed this.
