### ISSUE TITLE
Fungible? 

### ISSUE THREAD

**Issue by jandrieu** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#7]
In 03_4_Receiving_a_Transaction.md, it states
> Though the addresses are fairly private, transactions can be examined as they go in and out of addresses. This makes the funds ultimately fungible and makes the privacy vulnerable to statistical analysis.

Is it really the visibility of transactions that makes the funds fungible?

**Comment by shannona** [comment]
Addressed in PR #4.
