### ISSUE TITLE
How to sign a raw transaction? bitcoin core version v 0.17.0

### ISSUE THREAD

**Issue by vicenquintero** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#73]
Hey! I have read this tutorial: https://support.bitpay.com/hc/en-us/articles/115002990903-How-can-I-recover-funds-from-a-Bitcoin-Core-wallet-dat-file-without-having-the-entire-blockchain-downloaded-

I am trying to recover some funds transfered to my bitcoin core wallet without having to wait several days. There are many blockchains to be downloaded (only 4% in 3 days)

What to do? I can't sign the raw transaction. The system gives the following message: 
￼
signrawtransaction is deprecated and will be fully removed in v0.18. To use signrawtransaction in v0.17, restart bitcoind with -deprecatedrpc=signrawtransaction.
Projects should transition to using signrawtransactionwithkey and signrawtransactionwithwallet before upgrading to v0.18 (code -32)

I could, however, create the raw transaction.

I just need to sign the transaction and send it.

I already tried to import the private key in a blockchain account, but the balance is still "not spendable"

**Comment by shannona** [comment]
Unless you flagged it as RBF (https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/05_2_Resending_a_Transaction_with_RBF.md) you probably need to wait. 

More generally, we've already got #69 open about the need to switch over to the new methodology for signatures.
