### ISSUE TITLE
Alias btcblock does not produce a block number from the wget command.

### ISSUE THREAD

**Issue by nperalez** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#74]
Hello,

The second half of the btcblock alias does not seem to be working for me:
>alias btcblock="echo \\\`bitcoin-cli getblockcount 2>&1\\\`/\\\`wget - http://blockexplorer.com/testnet/q/getblockcount 2> /dev/null | cut -d : -f2 | rev | cut -c 2- | rev\\\`"

The getblockcount seems to work but the results I receive when I run the alias is "x/  " where x is the number of blocks on the longest chain. There is not input after "/".

Please advise.

**Comment by mkcisse** [comment]
@nperalez The link does not work anymore. A correction :
`alias btcblock="echo \\\`bitcoin-cli getblockcount 2>&1\\\`/\\\`wget -q -O - 'https://testnet.blockexplorer.com/api/status?q=getBlockCount' | cut -d , -f3 | cut -d : -f 2\\\`"

**Comment by SimoneBovi** [comment]
My latest PR should fix that: https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/pull/114

**Comment by shannona** [comment]
Alas, that testnet blockcount lookup is now dead too.

If someone turns one up, please let me know.

(And in the meantime, I'll flag this in [TODO.md](TODO.md).
