### ISSUE TITLE
Incorrect value of nSequence in relative timelock

### ISSUE THREAD

**Issue by gitzhou** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#75]
Hi there,

In part `Understand How CSV Really Works` of passage `9.3: Using CSV in Scripts`

> CSV has many of the same subtleties in usage as CLTV:
> - The nVersion field must be set to 2 or more.
> - The nSequence field must be set to less than 0xf0000000.
> - When CSV is run, there must be an operand on the stack that's between 0 and 0xf0000000-1.
> - Both the stack operand and nSequence must have the same value on the 23rd bit.
> - The nSequence must be greater than or equal to the stack operand.

Value `0xf0000000` in the 2nd and 3rd tip, I think it should be `0x80000000`

For my understanding

- `nSequence = 0xffffffff`, no timelock
- `0x80000000 <= nSequence < 0xffffffff`, indicates absolute timelock, `nLocktime` or `CLTV`, usually set to `0xfffffffe`
- `nSequence < 0x800000000`, indicates relative timelock, `nSequence` or `CSV`

Please help confirm this or correct me if I got wrong. Thanks  😄

**Comment by shannona** [comment]
A very belated reply, but yes, that's right. Thanks. (And fixed.)
