### ISSUE TITLE
Section 2:1 Setup Variables - Incorrect Variable BITCOIN

### ISSUE THREAD

**Issue by S4NT14G0** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#76]
The following command ```export BITCOIN=bitcoin-core-0.16.2``` causes

 ```$ wget https://bitcoin.org/bin/$BITCOIN/$BITCOINPLAIN-x86_64-linux-gnu.tar.gz -O ~user1/$BITCOINPLAIN-x86_64-linux-gnu.tar.gz```

```$ wget https://bitcoin.org/bin/$BITCOIN/SHA256SUMS.asc -O ~user1/SHA256SUMS.asc``` to fail.

The solution is to navigate to https://bitcoin.org/bin/ and find a bitcoin version that exists and rerun the export variable command.  

EG: ```export BITCOIN= bitcoin-core-0.16.3```

**Comment by SimoneBovi** [comment]
My latest PR should fix that: https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/pull/114

**Comment by matthiasdebernardini** [comment]
The beginning part of this section is really complicated and doesnt work on Debian 10 on DigitalOcean. 

I am following this and this https://www.digitalocean.com/community/tutorials/initial-server-setup-with-debian-10

Much simpler, maybe update to reflect this?

**Comment by shannona** [comment]
I've updated to 0.18.0 which works on testing. We'll go to 0.19.1 when we have the resources to do a more complete revision.
