### ISSUE TITLE
Add emoji to blockquotes to make them stand out more

### ISSUE THREAD

**Issue by ericcornelissen** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#89]
Inspired by [something this repository does](https://github.com/microsoft/terminal/blob/master/README.md#contributing) I want to propose adding emoji to the various blockquotes in order to make them stand out more (... than just the **bold** signal word). Another example of where this can be really beneficial is e.g. [Chapter 6 section 4 Write our Transaction](https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/06_4_Sending_a_Transaction_with_a_Locktime.md) where at the end two consecutive blockquotes appear. Without the emoji this may appear as a single thing, and the emoji can help readers more easily distinguish between the two.

In the table below I present a preview of what I mean, compared to the current situation, with examples from various chapters. Of course, the emojis I picked are also up for debate.

I'm curious to hear what peoples opinions are about adding this  to this project.

<table>
  <thead>
    <tr>
      <th>Current</th>
      <th>Updated</th>
      <th>Source</th>
    </tr>
  </thead>
    <tbody>
      <tr>
        <td>
          <blockquote><p><b>NOTE:</b> This is a draft in progress, so that I can get some feedback from early reviewers. It is not yet ready for learning.</p></blockquote>
        </td>
        <td>
          <blockquote><p>:information_source: <b>NOTE:</b> This is a draft in progress, so that I can get some feedback from early reviewers. It is not yet ready for learning.</p></blockquote>
        </td>
        <td>
          <a href="https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/03_1_Verifying_Your_Bitcoin_Setup.md">Chapter 3.1</a>
        </td>
      </tr>
      <tr>
        <td>
          <blockquote><p><b>WARNING:</b> The btcblock alias will not work correctly if you try to place it in your .bash_profile by hand, rather than using the...</p></blockquote>
        </td>
        <td>
          <blockquote><p>:warning: <b>WARNING:</b> The btcblock alias will not work correctly if you try to place it in your .bash_profile by hand, rather than using the...</p></blockquote>
        </td>
        <td>
          <a href="https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/03_1_Verifying_Your_Bitcoin_Setup.md">Chapter 3.1</a>
        </td>
      </tr>
      <tr>
        <td>
          <blockquote><p><b>VERSION WARNING:</b> This is an innovation from Bitcoin Core v 0.14.0. If you used our setup scripts, that's what you...</p></blockquote>
        </td>
        <td>
          <blockquote><p>:arrow_up: <b>VERSION WARNING:</b> This is an innovation from Bitcoin Core v 0.14.0. If you used our setup scripts, that's what you...</p></blockquote>
        </td>
        <td>
          <a href="https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/04_3_Creating_a_Raw_Transaction_with_Named_Arguments.md">Chapter 4.3</a>
        </td>
      </tr>
      <tr>
        <td>
          <blockquote><p><b>TESTNET vs MAINNET:</b> Remember that this tutorial generally assumes that you are using testnet. The btcblock...</p></blockquote>
        </td>
        <td>
          <blockquote><p>:link: <b>TESTNET vs MAINNET:</b> Remember that this tutorial generally assumes that you are using testnet. The btcblock...</p></blockquote>
        </td>
        <td>
          <a href="https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/03_1_Verifying_Your_Bitcoin_Setup.md">Chapter 3.1</a>
        </td>
      </tr>
  </tbody>
</table>

As for the _Sequence note_ (e.g. in [Chapter 4 section 2 Verify Your Raw Transaction](https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/04_2_Creating_a_Raw_Transaction.md)) I'm really lost on what emoji should be used (and related to the last part of this issue, if it should even be a blockquote).

* * *

Related to this, I feel like [the "M-OF-N VS N-OF-N" blockqoute in (e.g.*) chapter 6 section 1 Create the Addres](https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/06_1_Sending_a_Transaction_to_a_Multisig.md#create-the-address) is inconsistent with other usages of block quotes. But that might just be me :smile: 

<sup><i>* there is a similar one in [Chapter 6 section 2](https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/06_2_Spending_a_Transaction_to_a_Multisig.md)</i></sup>

**Comment by shannona** [comment]
Those are great, both for catching the eye and (as you say) separating adjacent comments. I'm in the process of adding them.
