### ISSUE TITLE
Confusing turn

### ISSUE THREAD

**Issue by jandrieu** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#9]
In Understanding the Bitcoin Transaction https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/04_2_Creating_a_Raw_Transaction.md#understand-the-bitcoin-transaction 
there is a sentence that doesn't quite make sense.

> For now, we won't worry about that, but the creation of a change address will be what turns the theory of this section until the actual use of the next subsection.

Not sure what it means to "turns the theory of this section until the actual use".

**Comment by shannona** [comment]
Thanks. Clarified now.
