### ISSUE TITLE
What's the meaning of triple single quotes

### ISSUE THREAD

**Issue by DinoStray** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#90]
In the chapter:

4.5: Sending Coins with Automated Raw Transactions

$ unfinishedtx=$(bitcoin-cli -named createrawtransaction inputs='''[]''' outputs='''{ "'$recipient'": 1.0 }''')

What's the meaning of triple single quotes like '''[]''' ?

**Comment by ConorOkus** [comment]
They are used to mark the start and end of a JSON array and JSON object

**Comment by shannona** [comment]
The info is in section 4.2, which I *think* is the first use of them.
