### ISSUE TITLE
`validateaddress` doesn't return a `pubkey` field anymore

### ISSUE THREAD

**Issue by justinmoon** [ChristopherA/Learning-Bitcoin-from-the-Command-Line#92]
`validateaddress` doesn't return a `pubkey` field anymore ([stackexchange](https://bitcoin.stackexchange.com/a/80754/85335)).

You should probably use `getaddressinfo` for [this step](https://github.com/ChristopherA/Learning-Bitcoin-from-the-Command-Line/blob/master/06_1_Sending_a_Transaction_to_a_Multisig.md#collect-remote-public-keys) instead

**Comment by shannona** [comment]
Thanks, we just resolved that as part of an update to that section.
